### ISSUE TITLE
Feedback - first Meteor app

### ISSUE THREAD

**Issue by jerrygraced** [jerrygraced/hawker-power#1]
@cbas @sevresbabylone would be great to get your thoughts on how the app can be improved

**Comment by cbas** [comment]
For future code reviews please open a pull request. Issues are good for general discussion but PR comments are best suited to review code.

**Comment by cbas** [comment]
Really nice work! Congrats on completing your project. :+1: 

Some suggestions:

The pull downs for sorting and areas are not functional. (Safari & Chrome)

Is it possible to split the templates and client/server code into their own files? I'm not familiar enough with Meteor but remember @nbiton showing how to do it.

What is the current status of automated testing in Meteor? I see Velocity is going through a transition. Not sure what's up. Would be nice to explore this as tests are critical when developing apps of any complexity.

**Comment by jerrygraced** [comment]
Thanks Seb!

1. To PR in future - noted 

2. Pull downs not functional - yes I haven't built them yet :)  wanted to concentrate on core database functionalities, especially the comment functions

3. Client/server split - yes definitely and also for security reasons

4. Automated testing - I didn't come across any during research, will check out Velocity

**Comment by jerrygraced** [comment]
Opening separate issues for the above:

- #4 Replace pull-down menus with animated off-canvas menu
- #5 Refactor and separate code into server- and client-side files
- #3 Set up Front-end testing
